### ISSUE TITLE
watch example please?

### ISSUE THREAD

**Issue by timc13** [mdreizin/webpack-glob#1]
I'm migrating over from your example in `webpack-config-stream` and I can't figure out how to setup a gulp task to watch

**Comment by mdreizin** [comment]
@timc13 

``` js
gulp.task('watch', [], function(callback) {
    var webpack = new WebpackGlob(compilerOptions, webpackOptions);

    webpack.watch('./src/**/webpack.config.js').then(function() {
        callback();
    }).catch(function(err) {
        callback(new gutil.PluginError('webpack', err));
    });
});
```

**Comment by timc13** [comment]
I assume that's for watching changes to the config file?

What about watching changes to JS to rebuild the bundle ? (per your example in the `webpack-config-stream` README)

Here's what I have so far:

```
gulp.task('build:webpack', function(callback) {
  var webpack = new webpackGlob(compilerOptions, configOptions)
  webpack.run(configFilename)
});

gulp.task('watch:webpack', ['build:webpack'], function(callback) {
  var webpack = new webpackGlob(compilerOptions, configOptions)
  gulp.watch(webpackWatch).on('change', function(event) {
    if (event.type === 'changed') {
      webpack.run(configFilename)
    }
  })
});
```

This doesn't seem to work - gulp gets stuck and I can't even `Ctrl+C` out of it.

**Comment by mdreizin** [comment]
@timc13 I'm working on new version which will fix some issues (`Ctrl+C` as well).

You don't need to call `webpack.run`, because `webpack-glob` uses `gaze` for watching.

**Comment by mdreizin** [comment]
@timc13 just call `webpack.watch` with `minimatch` pattern.

**Comment by timc13** [comment]
I'm sorry, maybe I'm missing something  I've tried an array of strings, a single string with comma-delimited globs and separate arguments and nothing seems to be triggering a rebuild.

Here's what I got:

```
gulp.task('build:webpack', function(callback) {
  var webpack = new webpackGlob(compilerOptions, configOptions)
  webpack.run(configFilename).then(function() {
    callback()
  }).catch(function(err) {
    callback(new gutil.PluginError('webpack', err))
  })
});

gulp.task('watch:webpack', ['build:webpack'], function(callback) {
  var webpack = new webpackGlob(compilerOptions, configOptions)
  webpack.watch(configFilename, './public/angular/**/*', '!./public/angular/**/*.html').then(function() {
    callback()
  }).catch(function(err) {
    callback(new gutil.PluginError('webpack', err))
  })
});
```

**Comment by mdreizin** [comment]
@timc13 I will fix that in new version, currently only one param is accepted.

**Comment by mdreizin** [comment]
@timc13 Here is preview https://github.com/mdreizin/webpack-cluster/blob/es6/src/CompilerAdapter.js#L99

**Comment by mdreizin** [comment]
@timc13 Also please see https://github.com/mdreizin/webpack-cluster/blob/es6/.gitdown/gulpfile.js#L38
