### ISSUE TITLE
Push a new version of the library with the peerDependency updated

### ISSUE THREAD

**Issue by pablolmiranda** [mdreizin/webpack-glob#48]
The version publish on the public npm registry still have a peerDependency to webpack-config 5.x.
Could you please push a new version of the library with the webpack-config 6.x peerDependency updated?

**Comment by mdreizin** [comment]
Hello, @pablolmiranda!

I'm sorrt for the late response.
I will fix this issue after my vacation.
Now I have limited access to internet, but if you create appropriate PR I will be able approve it and merge then.

**Comment by pablolmiranda** [comment]
@mdreizin there is no need to open a PR since the `package.json` has the latest version of webpack-config as a peerDependency. The only thing you need to do is publish a new version of the lib on NPM registry with the master branch code.
For some reason, your CI didn't do it.

**Comment by mdreizin** [comment]
Got it. I can do that only next week.

**Comment by pablolmiranda** [comment]
No problem, let me know when you push it.

**Comment by pablolmiranda** [comment]
@mdreizin any updates here?

**Comment by mdreizin** [comment]
@pablolmiranda I have pushed related changes, but `travis` has some [connectivity issues](https://www.traviscistatus.com/incidents/m41c9md5dg9z). Sorry for delay, please wait a little bit.
